### ISSUE TITLE
Private torrent

### ISSUE THREAD

**Issue by nimma0001** [shakilofficial0/UEHToR#2]
Can't download torrent from some private torrent site

**Comment by shakilofficial0** [comment]
Yes This One is For Public Torrent Only.

**Comment by ckvbalusu** [comment]
Actually Private tracker Support is very easy to add

**Comment by shakilofficial0** [comment]
You can show me the way how i could do that

**Comment by ckvbalusu** [comment]
https://raw.githubusercontent.com/Nenokkadine/Aria/master/aria2c.conf
This is the config i made.
Just replace this conf in your repo and Boom Private tracker Will work 100%

and on complete.sh file in your repo too has some issues too. It will upload the Downloading files too  with the Downloaded files  and reuploads the same files when they get downloaded
I Have a fix for that too
https://raw.githubusercontent.com/Nenokkadine/Aria/master/on-complete.sh
Use this it will Upload Correctly sir😊

**Comment by shakilofficial0** [comment]
okh Let me check

**Comment by ckvbalusu** [comment]
Worked?

**Comment by shakilofficial0** [comment]
i couldnt try that as heroku is blocking my project
