### ISSUE TITLE
Torrent files mirrored to gdrive already even if not yet finish downloading.

### ISSUE THREAD

**Issue by cocoamartin** [shakilofficial0/UEHToR#4]
It is mirrored to gdrive already. Is it going to get mirrored again if finish downloading?

**Comment by shakilofficial0** [comment]
basically the file get mirrored after finishing the download
the alga is Download the file->if token availble->Upload to gdrive

**Comment by shakilofficial0** [comment]
yes the filee will get mirrored if the download finish
other wise not

**Comment by cocoamartin** [comment]
This one I got
https://files.catbox.moe/5l6r0y.jpg

https://files.catbox.moe/cy696w.JPG

**Comment by cocoamartin** [comment]
confirmed it is recopying to a newer file after being downloaded
https://files.catbox.moe/str5m6.JPG - old
https://files.catbox.moe/cct5w0.JPG - new

**Comment by shakilofficial0** [comment]
so where problam has occured?

**Comment by cocoamartin** [comment]
I can send you my log. you have telegram?

**Comment by shakilofficial0** [comment]
please Explain the error
i am not seeing any error
on log and picture
Just explain and mark the point
like
File not uploading
one file uploading several times

You are trying to say that file uploading even the download process is not completed
Like think
is it really possible?!
and if the file upload first , it is an advantage for you. U can just easily download it from your drive. 
no need to wait for finish download ,upload bla bla.
Am i Right?!

**Comment by cocoamartin** [comment]
Sir, on the pic below just showing torrent is still downloading. Look at the time, bottom right 1:21am / July 11 
https://files.catbox.moe/jfrfgt.JPG

On this pic below you can see the folder/files uploaded on my gdrive already. That is why I can say it is being uploaded on my drive before the torrent finish downloading. You previously said before that it has to be uploaded first before being downloaded to drive.
https://files.catbox.moe/8grn71.JPG
https://files.catbox.moe/i1ew9p.JPG
https://files.catbox.moe/3kg2vu.JPG

I'm not an expert on this that is why i'm reporting this issue. 
If reporting this is making you mad, then sorry

**Comment by shakilofficial0** [comment]
Brother,look okh it is an issue thats true
but actual process i told you
why i dont know you are facing this
but i dont think it is a problam
cz your file is not corrupted
it doesnt make any sense 'file uploading first or last'
but if the file was corrupted or something just like this will make a hard sense
